name: Continuous Integration

on:
  push:
    branches:
      - '**'
    # Prevent recursive workflow runs from workflow-generated commits
    paths-ignore:
      - '.github/workflows/**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3' # Specify your Go version here

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./src/.../days/...
